version: '3.7'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - 3000:3000
    volumes:
        - '.:/app'
        - '/app/node_modules'
